# Generated by Django 4.2.30 on 2026-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_filter',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], default='ALL', max_length=15),
        ),
    ]
