# Generated by Django 4.2.30 on 2026-07-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('WELCOME_BONUS', 'Welcome Bonus'), ('FILTER_MATCH', 'Filter Match'), ('ADMIN_GRANT', 'Admin Grant'), ('ADMIN_DEDUCT', 'Admin Deduct'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('credits__gte', 0)), name='non_negative_credits'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='users_credi_user_id_f0389c_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['reference_id'], name='users_credi_referen_f724dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='credittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'FILTER_MATCH')), fields=('user', 'transaction_type', 'reference_id'), name='unique_filter_match_charge'),
        ),
    ]
