# Generated by Django 4.2.30 on 2026-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_credittransaction_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('suspended_until', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='match_mode',
            field=models.CharField(choices=[('VIDEO', 'Video & Audio'), ('TEXT', 'Text Only')], default='VIDEO', max_length=15),
        ),
    ]
