# Generated by Django 4.2.30 on 2026-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONNECT', 'Socket Connect'), ('DISCONNECT', 'Socket Disconnect'), ('JOIN_QUEUE', 'Join Queue'), ('MATCH_FOUND', 'Match Found'), ('SKIP', 'Skip Partner'), ('WEBRTC_SUCCESS', 'WebRTC Successful Connection'), ('WEBRTC_FAIL', 'WebRTC Failed Attempt')], max_length=20)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
